configs:
  ### Man QDT  ###
  10inch:
    window_size: { width: 1920, height: 1200 }
    frame_video: { x: 70, y: 70, width: 1780, height: 900 }
    switch_camera_button: { x: 770, y: 1030, width: 120, height: 40 }  # Thay cho label elevation_angle, cùng hàng ngang
    button1: { x: 900, y: 1030, width: 120, height: 40 }  # Thay cho label azimuth_angle, cách switch_camera_button 10px
    labels:
      distance: { x: 300, y: 1030, width: 200, height: 40, text: "Khoảng Cách" }
    text_edits:
      distance: { x: 510, y: 1030, width: 120, height: 40 }  # Bên phải label_distance, cách 10px
    video_widget: { x: 4, y: 4, width: 1772, height: 892 }
    camera:
      day:
        rtsp: "rtsp://admin:system123@192.168.100.24:554/Streaming/Channels/1"
      night:
        rtsp: "rtsp://admin:system123@192.168.100.25:554/ch0/stream0"
      local: 0
    colors:
      day: { background: "black", text: "white", label_background: "black", label_text: "white", border: "white" }
      night: { background: "white", text: "black", label_background: "white", label_text: "black", border: "black" }
    font_size: 14
    border_thickness: 3
    initial_values: { distance: 0 }
    serial_port: "/dev/ttyTHS0"
    serial_baudrate: 115200